# NumPy Basics: Arrays and Vectorized Computation

In [1]:
# Import NumPy with an alias
import numpy as np

In [2]:
# NumPy array is much faster than Python list object
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 34.1 ms, sys: 21.3 ms, total: 55.4 ms
Wall time: 55.6 ms
CPU times: user 647 ms, sys: 138 ms, total: 785 ms
Wall time: 789 ms


## The NumPy ndarray: A Multidimensional Array Object

In [3]:
# Generate some random data
data = np.random.randn(2, 3) # 2 rows x 3 columns
data

array([[ 1.12398351, -0.78250748, -0.70669931],
       [-1.02958103,  0.45260543,  0.08889141]])

In [4]:
# Multply each element by a constant
data * 10

array([[ 11.23983511,  -7.82507481,  -7.06699306],
       [-10.2958103 ,   4.5260543 ,   0.88891407]])

In [5]:
# Element-wise operation
data + data

array([[ 2.24796702, -1.56501496, -1.41339861],
       [-2.05916206,  0.90521086,  0.17778281]])

In [6]:
# Check vector dimension (row x column)
data.shape

(2, 3)

In [7]:
# To check data type
data.dtype

dtype('float64')

### Creating ndarrays

In [8]:
# np.array() takes a list as input
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [9]:
# It can also take a 2-dimensional list
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
# Check how many dimension
arr2.ndim

2

In [11]:
arr2.shape

(2, 4)

In [12]:
arr1.dtype

dtype('float64')

In [13]:
arr2.dtype

dtype('int64')

In [14]:
# Create 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
# Create 3 x 6 zeros (18 zeros)
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
# np.empty() returns near-zero values
np.empty((2, 3, 2))

array([[[1.8415115e-316, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]],

       [[0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000],
        [0.0000000e+000, 0.0000000e+000]]])

In [17]:
# Create 15 element array (0 - 14) because Python is zero-indexing
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

In [18]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [20]:
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr2.dtype

dtype('int32')

In [21]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [22]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [23]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [24]:
# Change dtype using .astype and np.int32
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [25]:
# Change string to float
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [26]:
# Change a variable's dtype with another variable's dtype
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with NumPy Arrays

In [27]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [28]:
# Multiplication
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [29]:
# Subtraction
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
# By a constant
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [31]:
# Take a square root
np.sqrt(arr) # equivalent to arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [32]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [33]:
# Logical condition of each vector element
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [34]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
# Get the 6th element of the vector. Remember, Python is a zero-indexing language.
arr[5]

5

In [36]:
# Slicing an array
arr[5:8]

array([5, 6, 7])

In [37]:
# Changing the value
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [38]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [39]:
# The original arr is replaced in-place
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [40]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [41]:
# Indexing a 2-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [42]:
arr2d[2][0]

7

In [43]:
# Alternative syntax for the above code
arr2d[0, 2]

3

In [44]:
# Indexing a 3-dimensional array
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [45]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# Use .copy() if we don't want to change in-place
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
arr3d[1, 0]

array([7, 8, 9])

In [49]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [50]:
x[0]

array([7, 8, 9])

#### Indexing with slices

In [51]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [52]:
# Slice the 2nd to the 6th
arr[1:6] # "1" is inclusive while "6" is exclusive

array([ 1,  2,  3,  4, 64])

In [53]:
# SLicing a 2-dimensional array
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
# Slicing the rows
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
# Slicing rows and columns
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [56]:
arr2d[1, :2]

array([4, 5])

In [57]:
arr2d[:2, 2]

array([3, 6])

In [58]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [59]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [60]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [61]:
data = np.random.randn(7, 4)
data

array([[-0.8251158 , -1.68819384,  0.38697883, -2.06821646],
       [ 0.71074004, -0.28342246,  0.30174579, -1.14661403],
       [-0.76636882,  0.59666113, -0.93979817,  0.18700178],
       [-0.21045278, -2.20825289,  0.62941956, -0.73898366],
       [ 1.51394395,  0.62327372, -0.65347256, -0.92330202],
       [ 0.6288616 , -0.31886342, -0.88009693, -0.7904694 ],
       [-0.87673051,  0.61189921,  0.27723924,  0.97581853]])

In [62]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [63]:
data[names == 'Bob']

array([[-0.8251158 , -1.68819384,  0.38697883, -2.06821646],
       [-0.21045278, -2.20825289,  0.62941956, -0.73898366]])

In [64]:
data[names == 'Bob', 2:]

array([[ 0.38697883, -2.06821646],
       [ 0.62941956, -0.73898366]])

In [65]:
data[names == 'Bob', 3]

array([-2.06821646, -0.73898366])

In [66]:
# != --> not equal to
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [67]:
# ~ --> negation or same as not equal to
data[~(names == 'Bob')]

array([[ 0.71074004, -0.28342246,  0.30174579, -1.14661403],
       [-0.76636882,  0.59666113, -0.93979817,  0.18700178],
       [ 1.51394395,  0.62327372, -0.65347256, -0.92330202],
       [ 0.6288616 , -0.31886342, -0.88009693, -0.7904694 ],
       [-0.87673051,  0.61189921,  0.27723924,  0.97581853]])

In [68]:
# We can put it into a variable
cond = names == 'Bob'
data[~cond]

array([[ 0.71074004, -0.28342246,  0.30174579, -1.14661403],
       [-0.76636882,  0.59666113, -0.93979817,  0.18700178],
       [ 1.51394395,  0.62327372, -0.65347256, -0.92330202],
       [ 0.6288616 , -0.31886342, -0.88009693, -0.7904694 ],
       [-0.87673051,  0.61189921,  0.27723924,  0.97581853]])

In [69]:
# "|" --> OR operation; "&" --> AND operation
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [70]:
data[mask]

array([[-0.8251158 , -1.68819384,  0.38697883, -2.06821646],
       [-0.76636882,  0.59666113, -0.93979817,  0.18700178],
       [-0.21045278, -2.20825289,  0.62941956, -0.73898366],
       [ 1.51394395,  0.62327372, -0.65347256, -0.92330202]])

In [71]:
# Change the element according to the condition we specify
data[data < 0] = 0
data

array([[0.        , 0.        , 0.38697883, 0.        ],
       [0.71074004, 0.        , 0.30174579, 0.        ],
       [0.        , 0.59666113, 0.        , 0.18700178],
       [0.        , 0.        , 0.62941956, 0.        ],
       [1.51394395, 0.62327372, 0.        , 0.        ],
       [0.6288616 , 0.        , 0.        , 0.        ],
       [0.        , 0.61189921, 0.27723924, 0.97581853]])

In [72]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.71074004, 0.        , 0.30174579, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.6288616 , 0.        , 0.        , 0.        ],
       [0.        , 0.61189921, 0.27723924, 0.97581853]])

### Transposing Arrays and Swapping Axes

In [73]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [74]:
# .reshape() will transform the array 
arr = arr.reshape(3, 5) # 3 x 5 array
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
# .T will transpose the array from 3 x 5 to 5 x 3 
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [76]:
arr = np.random.randn(6, 3)
arr

array([[ 1.6784747 , -0.23465515, -0.68602229],
       [-1.36010363, -0.03995938,  1.06260025],
       [ 0.56725601,  2.99657088, -1.37753737],
       [ 0.95006388, -0.38515394, -1.02929837],
       [-0.43570677, -0.0833323 , -0.88787772],
       [-1.18577895, -1.32078822,  0.40847501]])

In [77]:
# the dot product between 5 x 3 array and 3 x 5 will return a 3 x 3 array
np.dot(arr.T, arr)

array([[ 7.48747205,  2.59685947, -4.4535398 ],
       [ 2.59685947, 10.93586619, -4.07845231],
       [-4.4535398 , -4.07845231,  5.5119889 ]])

## Universal Functions: Fast Element-Wise Array Functions

In [78]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# Square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [80]:
# Exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [81]:
# Take the maximum value between x and y of each element
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x, y)

array([-0.46695223,  0.10148187, -0.39551448,  0.49658735,  1.22266899,
        0.32200682, -1.21914259,  0.99704163])

### Expressing Conditional Logic as Array Operations

In [82]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [83]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [84]:
# np.where is analogous to if else statement
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [85]:
arr = np.random.randn(4, 4)
np.where(arr > 0, 2, -2)

array([[-2,  2, -2, -2],
       [ 2, -2,  2, -2],
       [-2, -2, -2,  2],
       [-2,  2, -2,  2]])

In [86]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[-0.56776706,  2.        , -0.15243757, -0.21108316],
       [ 2.        , -0.55953078,  2.        , -0.53870829],
       [-0.99804323, -1.51062178, -0.94807223,  2.        ],
       [-0.40007801,  2.        , -1.02591511,  2.        ]])

### Mathematical and Statistical Methods

In [87]:
arr = np.random.randn(5, 4)
arr

array([[ 0.70873078,  1.00530607, -1.3314856 , -0.78106031],
       [-0.55216413, -2.24291669, -1.05707817, -0.15158743],
       [ 0.53309624,  1.00260379,  1.19669876,  0.18488373],
       [-0.26902697, -0.7802045 , -0.74309289,  0.6458325 ],
       [ 0.15214209,  1.59017233, -0.99071374, -2.10799415]])

In [88]:
# Using Python base function .mean()
arr.mean()

-0.19939291446743976

In [89]:
# Using NumPy np.mean() function
np.mean(arr)

-0.19939291446743976

In [90]:
arr.sum()

-3.9878582893487953

In [91]:
# axis=1 indicates operation is done column wise
arr.mean(axis=1)

array([-0.09962726, -1.00093661,  0.72932063, -0.28662296, -0.33909837])

In [92]:
# axis=0 indicates operation is done row wise
arr.sum(axis=0)

array([ 0.57277801,  0.574961  , -2.92567164, -2.20992566])

In [93]:
# Cummulative sum
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [94]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
# Row wise
arr.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [96]:
# Column wise
arr.cumprod(axis=1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

### Methods for Boolean Arrays

In [97]:
# True = 1; False = 0;
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values (sum of all Trues)

54

In [98]:
# .any() will return True if one of the element is True
bools = np.array([False, False, True, False])
bools.any()

True

In [99]:
# .all() will only return True if all elements are True
bools.all()

False

### Sorting

In [100]:
arr = np.random.randn(6)
arr

array([-0.69897008, -0.10301955, -1.56227429,  1.85076965,  0.51935125,
       -0.85177022])

In [101]:
arr.sort()
arr

array([-1.56227429, -0.85177022, -0.69897008, -0.10301955,  0.51935125,
        1.85076965])

In [102]:
arr = np.random.randn(5, 3)
arr

array([[-0.4235847 , -1.26745084,  0.69651391],
       [ 0.82817865,  0.41098536, -2.47974922],
       [ 1.78885721,  0.72096985, -0.68024278],
       [-0.2625733 ,  0.42320438, -0.679955  ],
       [ 0.74758073, -0.49479328, -1.04124829]])

In [103]:
arr.sort(1)
arr

array([[-1.26745084, -0.4235847 ,  0.69651391],
       [-2.47974922,  0.41098536,  0.82817865],
       [-0.68024278,  0.72096985,  1.78885721],
       [-0.679955  , -0.2625733 ,  0.42320438],
       [-1.04124829, -0.49479328,  0.74758073]])

In [104]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.6404546214957048

### Unique and Other Set Logic

In [105]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [106]:
# Get unique values from an array
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [107]:
# set() also returns unique values
sorted(set(names))

['Bob', 'Joe', 'Will']

## Linear Algebra

In [108]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [109]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [110]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [111]:
# Python base .dot() function
x.dot(y) # 2 x 3 dot 3 x 2 will return 2 x 2

array([[ 28.,  64.],
       [ 67., 181.]])

In [112]:
# NumPy np.dot() function
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

## Pseudorandom Number Generation

In [113]:
# Generate normally distributed random values
samples = np.random.normal(size=(4, 4))
samples

array([[ 0.69396901,  0.92063162,  0.72159251, -0.96329487],
       [ 1.08101051,  0.23734874,  0.5808634 , -0.11043036],
       [ 0.62120556, -0.07627728, -0.12669654,  0.59979981],
       [ 0.07886072, -0.46521245,  0.35798637, -0.62825925]])

In [114]:
rng = np.random.RandomState(1234) # for reproducibility
rng.randn(10)

array([ 0.47143516, -1.19097569,  1.43270697, -0.3126519 , -0.72058873,
        0.88716294,  0.85958841, -0.6365235 ,  0.01569637, -2.24268495])